# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # boxes at https://vagrantcloud.com/search.
#  config.vm.box = "alvistack/debian-testing"
  config.vm.box = "alvistack/ubuntu-24.04"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # TODO: map config
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive

    apt update --quiet
    apt install --quiet --yes

    curl -fsSL https://jehon.github.io/infrastructure/packages/jehon.deb -o jehon.deb
    apt install --quiet --yes ./jehon.deb
    apt update --quiet

    apt install -y docker.io
    systemctl enable --now docker.service

    apt install -y gitlab-runner

    # See docker group problem
  SHELL
end
