---
- name: Setup p2p
  # see /var/lib/deluged/config/core.json
  block:
    - name: Install p2p packages
      ansible.builtin.apt:
        pkg:
          - deluged
          - deluge-web

    # Port is forwarded by ssh

    - name: Create folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: debian-deluged
        group: debian-deluged
        mode: "0775"
      loop:
        - /srv/p2p/downloaded
        - /srv/p2p/downloading
        - /srv/p2p/watch

    - name: Create link to config
      ansible.builtin.file:
        path: /srv/p2p/config
        src: /var/lib/deluged/config
        state: link

    - name: Add dev to debian-deluged
      ansible.builtin.user:
        name: { { dev_user } }
        groups: debian-deluged
        append: true
