---

- name: "Update repo {{ path + ' @' + url + ' #' + (version | default('main')) }}"
  ansible.builtin.git:
    dest: "{{ path }}"
    repo: "{{ url }}"
    version: "{{ version | default('main') }}"
    clone: true
    update: true
    force: "{{ clean | default(true) }}"
    accept_newhostkey: true
    depth: 1
    recursive: true
    single_branch: true
  environment:
    GIT_TERMINAL_PROMPT: "0"
  # https://stackoverflow.com/a/72812772/1954789
  register: jh_git_repo_clone
  failed_when:
    - jh_git_repo_clone.failed
    - not 'Local modifications exist' in jh_git_repo_clone.msg

- name: Configure push url
  when: push is defined
  ansible.builtin.command: git remote set-url --push origin "{{ push }}"
  args:
    chdir: "{{ path }}"
  tags:
    - skip_ansible_lint
