#!/usr/bin/env bash

set -o errexit
set -o pipefail
shopt -s nullglob

_SD="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source-path=SCRIPTDIR
. "${_SD}"/../../../../bin/lib.sh

stackFolder="${_SD}/stacks/home"

cd "${stackFolder}"

case "$LOCATION" in
"home" | "external")
    docker compose up -d
    ;;
*)
    docker compose stop
    ;;
esac
