---
#
# Desktop side
#
- name: Setup Desktop env
  # TODO: detect desktop is enabled....
  when: false
  block:
    - name: Install desktop packages
      ansible.builtin.apt:
        pkg:
          - copyq
          - digikam
          - ffmpegthumbnailer # Thumbnails for movies
          - gnome-network-displays
          - gnome-shell-extensions
          - gthumb # Print multiple images on one page
          - libfuse2 # pcloud
          - solaar

    - name: "Ensure installed snap"
      when: not virtual
      with_items:
        - firefox
        - gimp
        - ksnip
        - mkvtoolnix-jz
        - spotify
        - whatsapp-for-linux # Personnal (conf call)
        - vlc
      community.general.snap:
        name: "{{ item }}"
        state: present

    - name: "Ensure installed snap (classic)"
      when: not virtual
      with_items:
        - code
      community.general.snap:
        name: "{{ item }}"
        state: present
        classic: true
    # node in snap? could not access pCloudDrive... but still the best option

    - name: "Ensure installed snap (special) "
      when: not virtual
      with_items:
        - subtitle-edit
      community.general.snap:
        name: "{{ item }}"
        state: present
        channel: edge

    # TODO: what to do with this?
    # - name: Setup Gnome and other customizations
    #   when: not virtual
    #   become: true
    #   become_user: "{{ user }}"
    #   ansible.builtin.command:
    #     cmd: /usr/bin/jh-setup-user-profile
    #   register: result
    #   changed_when: "'[modified]' in result.stdout"
