---

- name: Build artifacts
  # Specifying stuff here do not define them in the inventory
  # and so this particular host is not taken into account
  # when setup.yml on all hosts...
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
    - name: Generate dev-config.yml for github homepage
      ansible.builtin.template:
        src: "templates/setup-dev-config.json"
        dest: "tmp/dev-config.json"
        mode: "0644"
