#!/usr/bin/env bash

prjRoot="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source-path=SCRIPTDIR/
. "${prjRoot}/bin/lib.sh"

# Initial setup from dhcp ip:
#
# -e "ansible_host=192.168.1.5"
#

PLAYBOOK="${PLAYBOOK:-"setup.yml"}"
hosts=("$@")
args=()

runIt() {
	$withSudo "${prjRoot}"/tmp/python/common/bin/ansible-playbook --diff "${PLAYBOOK}" "${args[@]}" "$@"
}

requireSudo() {
	if [ -n "$1" ]; then
		echo "Require sudo password for $host"
	else
		echo "Require sudo password"
	fi
	# withSudo="sudo --preserve-env=PATH,PYTHONPATH"
	# TODO: should --ask-become-pass ?
	args+=("--ask-become-pass")
}

if [ ! -r ~/restricted/ansible-encryption-key ]; then
	# shellcheck disable=SC2174
	mkdir --mode=0700 -p ~/restricted
	touch ~/restricted/ansible-encryption-key
	jh_fatal "Key is not defined at ~/restricted/ansible-encryption-key"
fi

make dependencies

export PYTHONPATH="${prjRoot}/tmp/python/common:$PYTHONPATH"
cd infrastructure || exit

withSudo=""

if ((${#hosts} > 0)); then
	for host in "${hosts[@]}"; do
		case "$host" in
		"" | "dev")
			requireSudo "$host"
			;;
		esac
	done
else
	requireSudo
fi

# Join the array with comma
#   https://stackoverflow.com/a/9429887/1954789
hostsCommaList=$(
	IFS=,
	echo "${hosts[*]}"
)
runIt --limit "$hostsCommaList"
