#!/usr/bin/env bash

prjRoot="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source-path=SCRIPTDIR/
. "${prjRoot}/bin/lib.sh"

# Initial setup from dhcp ip:
#
# -e "ansible_host=192.168.1.5"
#

PLAYBOOK="${PLAYBOOK:-"setup.yml"}"
hosts=("$@")

runIt() {
    $withSudo "${prjRoot}"/tmp/python/common/bin/ansible-playbook --diff "${PLAYBOOK}" "$@"
}

requireSudo() {
    if [ -n "$1" ]; then
        echo "Require sudo password for $host"
    else
        echo "Require sudo password"
    fi
    withSudo="sudo --preserve-env=PATH,PYTHONPATH"
    # ARGS+=("--ask-become-pass")
}

if [ ! -r ~/restricted/ansible-encryption-key ]; then
    mkdir -p ~/restricted
    touch ~/restricted/ansible-encryption-key
    jh_fatal "Key is not defined at ~/restricted/ansible-encryption-key"
fi

make dependencies

export PYTHONPATH="${prjRoot}/tmp/python/common:$PYTHONPATH"
cd infrastructure || exit

withSudo=""

if ("${#hosts}"); then
    for host in "${hosts[@]}"; do
        case "$host" in
        "" | "dev")
            requireSudo "$host"
            ;;
        esac
    done
else
    requireSudo
fi

# TODO: What condition here?
if [ -n "$HOST" ]; then
    runIt --limit "${hosts[0]}"
else
    # TODO: should --ask-become-pass ?
    runIt
fi
