#!/usr/bin/env bash

SWD="$(dirname "$( realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=SCRIPTDIR/../bin
. "${SWD}/bin/lib.sh"

if [ -z "$1" ]; then
    jh_fatal "Need [host...]"
fi

PLAYBOOK="setup.yml"

export PYTHONPATH="${JH_PKG_FOLDER}/tmp/python/common:$PYTHONPATH"
cd infrastructure

while [ -n "$1" ]; do
    HOST="$1"
    shift
    "${JH_PKG_FOLDER}"/tmp/python/common/bin/ansible-playbook --limit "${HOST}" "${PLAYBOOK}" | jh-tag-stdin "${HOST}"
done
