#!/usr/bin/bash

SWD="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=SCRIPTDIR/../bin
. "${SWD}/bin/lib.sh"

host="$1"
shift

if [ -z "$1" ]; then
    # host is already shifted
    jh_fatal "Need [host] [source]"
fi

while [ -n "$1" ]; do
    source="$1"
    dest="${source#packages/*/}"
    jh_value "SOURCE" "${source}"
    jh_value "dest" "${dest}"

    if [ "${host}" == "dev" ]; then
        sudo cp -f "${source}" "/${dest}"
    else
        rsync -i --checksum "${source}" "root@${host}:/${dest}"
    fi
    # scp "$SOURCE" "root@$HOST:/${dest}"
    ok "Uploaded to ${dest}"
    shift
done
