---

- name: Dump variables
  hosts: all
#  gather_facts: false

  tasks:
    - name: Initialize
      ansible.builtin.include_role:
        name: jh_init

    - name: Debug jehon
      debug:
        var: jehon

    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

    # - name: Display all variables/facts known for a host {{ inventory_hostname }}
    #   ansible.builtin.debug:
    #     var: hostvars[inventory_hostname]

    - name: Display ansible_pkg_mgr
      ansible.builtin.debug:
        var: ansible_pkg_mgr

    - name: Display ansible_distribution
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Display ansible_lsb
      ansible.builtin.debug:
        var: ansible_lsb.id
