---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

#
# We need to pass through all this for handlers to run only once
#

- name: Setup systems
  hosts: all
  tasks:
    - name: Setup jh_basis
      when: "'grp_jehon' in group_names"
      ansible.builtin.include_role:
        name: jh_repositories

    - name: Setup Jehon Service Headless
      when: jehon_headless
      ansible.builtin.include_role:
        name: jehon_service_headless

    # Need service headless for netplan
    - name: Setup networking
      when: "'grp_jehon' in group_names"
      ansible.builtin.include_role:
        name: jh_network

    - name: Setup monitoring
      when: grafana_template | length > 0
      ansible.builtin.include_role:
        name: jh_monitoring

    - name: Setup cloud
      ansible.builtin.include_role:
        name: jh_cloud

    - name: Setup host dev
      when: inventory_hostname == "dev"
      ansible.builtin.include_role:
        name: host_dev

    - name: Setup host kiosk
      when: inventory_hostname == "kiosk"
      ansible.builtin.include_role:
        name: host_kiosk

    - name: Setup host piscine
      when: inventory_hostname == "piscine"
      ansible.builtin.include_role:
        name: host_piscine

    - name: Setup host synology
      when: inventory_hostname == "synology"
      ansible.builtin.include_role:
        name: host_synology
