---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

# NAS: ansible_os_family: OtherLinux

- name: Upgrade all systems
  hosts: grp_jehon
  tasks:
    - name: Update packages
      when: ansible_pkg_mgr == "apt"
      block:
        - name: Update and upgrade apt packages
          ansible.builtin.apt:
            update_cache: true
            upgrade: full
            autoclean: true
            autoremove: true
            purge: true

    - name: Update git's
      # TODO: detect changed_when
      ansible.builtin.shell: >-
        if [ -x /usr/bin/jh-repository-update ]; then
          /usr/bin/jh-repository-update
        fi
      changed_when: true
