#!/usr/bin/env bash

set -o errexit
set -o pipefail
shopt -s nullglob

target="$(jh-fs "file-to-path" "$0")"

case "$1" in
"configure" | "")
    (
        cat <<EOS
#
# Generated by $0
#

X-Repolib-Name: Docker (jehon)
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(lsb_release -cs)
Components: stable
Enabled: yes
Signed-By: /usr/share/keyrings/jehon-docker-ubuntu.gpg
EOS

    ) | jh-install-file "${target}"
    ;;
"remove")
    rm -f "${target}"
    ;;
esac
