---

- name: Grafana - Install api key
  ansible.builtin.template:
    src: "{{ role_path }}/templates/grafana-api-key.txt"
    # TODO: move that to restricted + add grafana user to jehon_secrets
    dest: /etc/jehon/grafana-api-key.txt
    mode: "0640"
    owner: grafana-agent
    group: jehon_secrets
  notify: jehon_service_grafana.changed

# - name: Grafana - Install config river
#   ansible.builtin.template:
#     src: "{{ role_path }}/templates/grafana.river"
#     dest: /etc/grafana-agent-flow.river
#     mode: "0640"
#     owner: grafana-agent-flow
#     group: jehon_secrets
#   notify: jehon_service_grafana.changed

- name: Grafana - Install config river
  ansible.builtin.template:
    src: "{{ role_path }}/templates/grafana.yaml"
    dest: /etc/grafana-agent.yaml
    mode: "0640"
    owner: grafana-agent
    group: jehon_secrets
  notify: jehon_service_grafana.changed

- name: Grafana - Enable service
  when: not virtual
  ansible.builtin.systemd:
    name: grafana-agent
    state: started
    enabled: true
