---
- name: Install kiosk packages
  ansible.builtin.apt:
    pkg:
      - jehon-service-headless

- name: Install site.config
  ansible.builtin.template:
    src: "site.conf"
    dest: "/etc/jehon/site.conf"
    owner: root
    group: root
    mode: "0644"

- name: Install secrets files
  with_items:
    - cryptomedic.sh
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/srv/stack/secrets/{{ item }}"
    owner: "jehon-daemon"
    group: jehon-secrets
    mode: "0750"

- name: Allow database connections
  # https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
  # with_items:
  #   # From Web Cloud
  #   - "2001:41d0:1:1b00:213:186:33:4"
  #   - "213.186.33.4"
  community.general.ufw:
    rule: allow
    name: jehon-mysql
    # later: delete this rule
    # delete: true
