---
- name: Install secrets files
  with_items:
    - cryptomedic.sh
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/srv/stack/secrets/{{ item }}"
    owner: "jehon-daemon"
    group: jehon-secrets
    mode: "0750"

- name: Allow database connections
  # https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
  # with_items:
  #   # From Web Cloud
  #   - "2001:41d0:1:1b00:213:186:33:4"
  #   - "213.186.33.4"
  community.general.ufw:
    rule: allow
    name: jehon-mysql
    # later: delete this rule
    # delete: true

- name: Setup cloud
  ansible.builtin.include_role:
    name: jh_cloud

- name: Setup stack
  ansible.builtin.include_role:
    name: jh_stack
  vars:
    jh_stack_git_slug: "jehon/stack-vps"
