- name: Setup stack
  block:
    - name: Install git repo
      become: true
      become_user: jehon-daemon
      become_method: ansible.builtin.su
      ansible.builtin.git:
        repo: "https://{{ jehon_remote_gitlab_username }}:{{ jehon_remote_gitlab_token }}@gitlab.com/{{ jh_stack_git_slug }}"
        dest: /home/jehon-daemon/stack
        version: main
        force: true
      notify: jh_stack.reload

    - name: Install jehon-service-stack
      ansible.builtin.apt:
        pkg:
          - jehon-service-stack
