- name: Setup stack
  block:
    - name: Install git repo
      ansible.builtin.git:
        repo: https://{{ jehon.gitlab.username | urlencode }}:{{ gitlab_token | urlencode }}@gitlab.com/${stack_git_slug}
        dest: /home/jehon-daemon/stack
        version: main
      notify: jh_stack.reload

    - name: Install jehon-service-stack
      ansible.builtin.apt:
        pkg:
          - jehon-service-stack
