- name: Create targets folders
  loop:
    # TODO: Relative to {{ jehon_project_dir }}
    - tmp
    - tmp/publish
    - tmp/artifacts
  ansible.builtin.file:
    state: directory
    dest: "{{ jehon_project_dir }}/{{ item }}"
    owner: "{{ jehon_dev_user }}"
    group: "{{ jehon_dev_user }}"
    mode: "0750"

- name: Generate artifacts for github homepage
  loop:
    - dev-config.json
  ansible.builtin.template:
    src: "templates/{{ item }}"
    dest: "{{ jehon_project_dir }}/tmp/publish/{{ item }}"
    mode: "0644"

- name: Generate artifacts locally
  loop:
    - user-data
  ansible.builtin.template:
    src: "templates/{{ item }}"
    dest: "{{ jehon_project_dir }}/tmp/artifacts/{{ item }}"
    mode: "0644"
