---

argument_specs:
  main:
    options:
      path:
        type: string
        required: true
      url:
        type: string
        required: true
      push:
        type: string
        required: false
      version:
        type: string
        required: false
        default: 'main'
      clean:
        type: boolean
        required: false
        default: true
