---
- name: Install packages
  when: ansible_pkg_mgr == "apt"
  block:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_facts_module.html
    - name: check packages
      ansible.builtin.package_facts:
        manager: auto

    ############################################
    #
    # Jehon.deb
    #
    ############################################

    # We need this one to be installed first, because next line will depend on it
    - name: "Install jehon.deb from the web"
      when: "'jehon' not in ansible_facts.packages"
      ansible.builtin.apt:
        deb: "https://jehon.github.io/packages/jehon.deb"
      notify: jh_repositories.indexes
      register: jehon_basis_jehon_deb
      # Example: [run]   msg: Breaks existing package 'jehon-hardware-wsl' dependency jehon (<= 2023.06.28.14.53.03)
      failed_when: >
        jehon_basis_jehon_deb.failed
        and (
          ('A later version is already installed' != jehon_basis_jehon_deb.msg)
          and (' dependency jehon (' not in jehon_basis_jehon_deb.msg)
        )

    ############################################
    #
    # Tools
    #
    ############################################


    ############################################
    #
    # Repositories
    #
    ############################################

    - name: Setup mopidy repository
      when: jehon_repo_mopidy
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-mopidy-repository"
      notify: jh_repositories.indexes
      register: result
      changed_when: "'[modified]' in result.stdout"

    - name: Setup Debian
      # TODO: Quid on raspbian ? actually raspberry pi does not have jehon_testing
      when: ansible_distribution == "Debian"
      block:
        - name: Setup debian repositories
          when: jehon_testing > 0
          ansible.builtin.command:
            cmd: "/usr/sbin/jh-install-debian-testing {{ jehon_testing }}"
          register: result
          notify: jh_repositories.indexes
          changed_when: "'[modified]' in result.stdout"

    - name: Refresh indexes for jehon
      ansible.builtin.meta: flush_handlers

    ############################################
    #
    # Repositories and packages
    #
    ############################################

    - name: Setup docker repository and packages
      when: jehon_repo_docker
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-docker"
      register: result
      changed_when: >
        '[modified]' in result.stdout
        or 'Preparing to unpack' in result.stdout

    ############################################
    #
    # Packages
    #
    ############################################

    - name: Install jehon-hardware*.deb
      when: jehon_hardware | length > 0
      block:
        - name: "Ensure jehon-hardware is present for hardware {{ jehon_hardware }}"
          ansible.builtin.apt:
            pkg:
              - "jehon-hardware-{{ jehon_hardware }}"
