- name: "In 00_variables > Get facts on current container"
  community.docker.current_container_facts:

- name: "In 00_variables > [is_virtual]"
  block:
    - name: "In 00_variables > [is_virtual]"
      block:
        - name: "In 00_variables > [is_virtual] Calculate"
          ansible.builtin.set_fact:
            virtual: "{{ ansible_module_running_in_container }}"

    - name: "In 00_variables > [is_virtual] Dump"
      ansible.builtin.debug:
        var: virtual

- name: "In 00_variables > [jh_with_snap]"
  block:
    - name: "In 00_variables > [jh_with_snap] Test command"
      ansible.builtin.command: snap --version
      changed_when: false

    - name: "In 00_variables > [jh_with_snap] Calculate"
      ansible.builtin.set_fact:
        jh_with_snap: true

  rescue:
    - name: "In 00_variables > [jh_with_snap] Not found"
      ansible.builtin.set_fact:
        jh_with_snap: false

- name: "In 00_variables > [jh_with_snap] Dump"
  ansible.builtin.debug:
    var: jh_with_snap
