- name: "{{ j_task }} | Get facts on current container"
  community.docker.current_container_facts:

- name: "{{ j_task }} | [is_virtual]"
  block:
    - name: "{{ j_task }} | [is_virtual]"
      block:
        - name: "{{ j_task }} | [is_virtual] Calculate"
          ansible.builtin.set_fact:
            virtual: "{{ ansible_module_running_in_container }}"

    - name: "{{ j_task }} | [is_virtual] Dump"
      ansible.builtin.debug:
        var: virtual

- name: "{{ j_task }} | [jh_with_snap]"
  block:
    - name: "{{ j_task }} | [jh_with_snap] Test command"
      ansible.builtin.command: snap --version
      changed_when: false

    - name: "{{ j_task }} | [jh_with_snap] Calculate"
      ansible.builtin.set_fact:
        jh_with_snap: true

  rescue:
    - name: "{{ j_task }} | [jh_with_snap] Not found"
      ansible.builtin.set_fact:
        jh_with_snap: false

- name: "{{ j_task }} | [jh_with_snap] Dump"
  ansible.builtin.debug:
    var: jh_with_snap
