- name: "In {{ j_ctx }} > Install packages"
  when: ansible_pkg_mgr == "apt"
  block:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_facts_module.html
    - name: "In {{ j_ctx }} > Gather facts"
      ansible.builtin.package_facts:
        manager: auto

    - name: "In {{ j_ctx }} > Update system"
      block:
        - name: "In {{ j_ctx }} > Update cache if too old"
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-cache_valid_time
          ansible.builtin.apt:
            cache_valid_time: 3600 # seconds -> 1 hour
            autoclean: true
          register: jh_01_basis_initial_apt_update
          # This does not make change!
          changed_when: false

        - name: "In {{ j_ctx }} > Run upgrade"
          when: jh_01_basis_initial_apt_update.cache_updated
          ansible.builtin.apt:
            upgrade: dist
          # We don't want to track those changes
          changed_when: false
