- name: "{{ j_task }} | Install packages"
  when: ansible_pkg_mgr == "apt"
  block:
    - name: "{{ j_task }} | Install jehon.deb"
      block:
        - name: "{{ j_task }} | Dump jh_deb_url"
          ansible.builtin.debug:
            var: jh_deb_url

        # We need this one to be installed first, because next line will depend on it
        - name: "{{ j_task }} | Install jehon.deb"
          when: "'jehon' not in ansible_facts.packages"
          ansible.builtin.apt:
            deb: "{{ jh_deb_url }}"
            # This will be done by the jh_01_basis.indexes at the correct time...
            update_cache: false
          notify: jh_01_basis.indexes
          register: jehon_basis_jehon_deb
          # Example: [run]   msg: Breaks existing package 'jehon-hardware-wsl' dependency jehon (<= 2023.06.28.14.53.03)
          failed_when: >
            jehon_basis_jehon_deb.failed
            and (
              ('A later version is already installed' != jehon_basis_jehon_deb.msg)
              and (' dependency jehon (' not in jehon_basis_jehon_deb.msg)
            )

    ############################################
    #
    # Update repository if necessary
    #
    ############################################
    - name: "{{ j_task }} | Update repositories if necessary..."
      ansible.builtin.meta: flush_handlers

    ############################################
    #
    # Packages jehon-*
    #
    ############################################
    - name: "{{ j_task }} | Install jehon-hardware-*"
      block:
        - name: "{{ j_task }} | Calculate jehon_hardware"
          block:
            - name: "{{ j_task }} | Set default value for jehon_hardware"
              when: jehon_hardware is not defined
              ansible.builtin.set_fact:
                jehon_hardware: ""

            - name: "{{ j_task }} | Set jehon_hardware to wsl"
              # https://stackoverflow.com/a/78046212/1954789
              when: '"microsoft" in ansible_facts["kernel"]'
              ansible.builtin.set_fact:
                jehon_hardware: wsl

            - name: "{{ j_task }} | Set jehon_hardware to raspberrypi"
              when: ansible_architecture == "aarch64" # vs. amd64 for laptop
              ansible.builtin.set_fact:
                jehon_hardware: raspberrypi

            - name: "{{ j_task }} | Set jehon_hardware to docker"
              # https://docs.ansible.com/ansible/latest/collections/community/docker/current_container_facts_module.html
              when: ansible_module_running_in_container
              ansible.builtin.set_fact:
                jehon_hardware: docker

            # TODO: jehon_hardware = desktop ???

        - name: "{{ j_task }} | Dump jehon_hardware"
          ansible.builtin.debug:
            var: jehon_hardware

        - name: "{{ j_task }} | Install hardware package"
          when: jehon_hardware | length > 0
          block:
            - name: "{{ j_task }} | Ensure jehon-hardware is present for hardware {{ jehon_hardware }}"
              ansible.builtin.apt:
                pkg:
                  - "jehon-hardware-{{ jehon_hardware }}"
