- name: Add IP address to /etc/hosts
  loop: "{{ query('ansible.builtin.varnames', '^jehon_ip_.+') | replace('jehon_ip_', '') }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    # Match: <ip|ipv6> <host>.honlet <legacy> # ansible
    regexp: ".* {{ item }}.honlet .* # ansible"
    # Set: <hostname>.honlet and <hostname> alias
    line: "{{ vars['jehon_ip_' + item] }} {{ item }}.honlet {{ item }} # ansible"
    state: present
  register: _
  # On docker, the /etc/hosts is not writable
  # complete message: [Errno 16] Device or resource busy
  failed_when: >
    _.failed
    and "[Errno 16]" not in _.msg
