# TODO
- name: "In 30_user_dev"
  when: jehon_dev_user is defined and jehon_dev_user
  block:
    - name: "In 30_user_dev > Install package jehon-service-dev"
      ansible.builtin.apt:
        pkg:
          - jehon-service-dev

    - name: "In 30_user_dev > Create user"
      ansible.builtin.user:
        name: "{{  jehon_dev_user }}"
        shell: /usr/bin/zsh
        generate_ssh_key: true

    - name: "In 30_user_dev > Set password"
      when: jehon_dev_password is defined and jehon_dev_password
      ansible.builtin.user:
        name: "{{ jehon_dev_user }}"
        # See https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
        update_password: on_create
        password: "{{ jehon_dev_password | password_hash('sha512', 'salt') }}"

    - name: "In 30_user_dev > Create restricted folder"
      # Required for later operations
      ansible.builtin.file:
        state: directory
        dest: /home/{{ jehon_dev_user }}/restricted/
        owner: "{{ jehon_dev_user }}"
        group: jehon-secrets
        mode: "0750"

    - name: "In 30_user_dev > Set git user for dev user"
      when: jehon_remote_github_email is defined and jehon_remote_github_email
      block:
        - name: "In 30_user_dev > Set gitconfig files"
          ansible.builtin.template:
            src: "{{ item }}"
            dest: /home/{{ jehon_dev_user }}/.{{ item }}
            owner: "{{ jehon_dev_user }}"
            group: "{{ jehon_dev_user }}"
            mode: "0640"
          with_items:
            - gitconfig
            - gitconfig-github
            - gitconfig-gitlab
