# - name: Install packages
#   when: ansible_pkg_mgr == "apt"
#   block:

# ############################################
# #
# # Configure universe repository
# #
# ############################################

# - name: Add ubuntu universe
#   when: ansible_distribution == "Ubuntu"
#   ansible.builtin.apt_repository:
#     repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe restricted multiverse"
#     state: present
#     update_cache: true

############################################
#
# Packages (too volatile one)
#
############################################
