- name: "{{ j_task }} | Handle configuration"
  block:
    - name: "{{ j_task }} | Configure"
      when: jehon_grafana_token
      block:
        - name: "{{ j_task }} | Install packages"
          when: ansible_pkg_mgr == "apt"
          ansible.builtin.apt:
            name:
              - jehon-service-headless

        - name: "{{ j_task }} | Install config"
          ansible.builtin.template:
            src: "config.alloy"
            dest: /etc/alloy/config.alloy
            owner: alloy
            group: jehon-daemon
            mode: "0640"

    ## ELSE ##
    - name: "{{ j_task }} | Remove config"
      when: jehon_grafana_token == ""
      with_items:
        - /etc/alloy/config.alloy
      ansible.builtin.file:
        state: absent
        dest: "{{ item }}"

  notify: jh_01_basis.alloy_reload
