- name: "In 70_cloud > Handle cloud configuration"
  block:
    - name: "In 70_cloud > Configure cloud"
      when: jehon_cloud_type
      block:
        - name: "In 70_cloud > Install packages (fuse)"
          when: ansible_pkg_mgr == "apt"
          ansible.builtin.apt:
            name:
              - fuse3

        - name: "In 70_cloud > Install config"
          ansible.builtin.template:
            src: "rclone.conf"
            dest: /etc/jehon/rclone.conf
            owner: root
            group: jehon-daemon
            mode: "0640"

    ## ELSE ##
    - name: "In 70_cloud > Remove config"
      when: jehon_cloud_type == ""
      with_items:
        - /etc/jehon/rclone.conf
        - /var/lib/docker-plugins/rclone/config/rclone.conf
      ansible.builtin.file:
        state: absent
        dest: "{{ item }}"
      notify: jh_01_basis.systemctl_reload
  #
  # TODO: enable various mounts
  #
