############################################
#
# Docker:
#
# 2024-07-11: deb packages have apparmor problems
# 2024-09-04: VPS is running on snap
#             Forcing removal of docker packages
# 2024-10-05: Switching to docker-ce.deb
#              - remove --purge snap
#              - reboot
#              - install deb's
#
- name: "In {{ j_ctx }} > Remove Docker snap if present"
  when: jh_with_snap
  block:
    - name: "In {{ j_ctx }} > Normal snaps"
      community.general.snap:
        state: absent
        name:
          - docker

- name: "In {{ j_ctx }} > Install jehon-service-docker"
  when: ansible_pkg_mgr == "apt"
  ansible.builtin.apt:
    state: present
    pkg:
      - jehon-service-docker

- name: "In {{ j_ctx }} > Install rclone config for plugin"
  when: ansible_pkg_mgr == "apt"
  ansible.builtin.template:
    src: rclone.conf
    dest: /var/lib/docker-plugins/rclone/config/rclone.conf
    owner: root
    group: jehon-secrets
    mode: "0700"

- name: "In {{ j_ctx }} > Authenticate to GitLab"
  when: jehon_remote_gitlab_token
  become: true
  become_user: jehon-daemon
  become_method: ansible.builtin.su
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_login_module.html
  # https://docs.gitlab.com/ee/user/packages/container_registry/authenticate_with_container_registry.html
  community.docker.docker_login:
    registry_url: registry.gitlab.com
    username: "{{ jehon_remote_gitlab_username }}"
    password: "{{ jehon_remote_gitlab_token }}"
