############################################
#
# Docker:
#
# 2024-07-11: deb packages have apparmor problems
# 2024-09-04: VPS is running on snap
#             Forcing removal of docker packages
# 2024-10-05: Switching to docker-ce.deb
#              - remove --purge snap
#              - reboot
#              - install deb's
#
- name: "{{ j_task }} | Remove Docker snap if present"
  when: jh_with_snap
  block:
    - name: "{{ j_task }} | Normal snaps"
      community.general.snap:
        state: absent
        name:
          - docker

- name: "{{ j_task }} | Install jehon-service-docker"
  when: ansible_pkg_mgr == "apt"
  ansible.builtin.apt:
    state: present
    pkg:
      - jehon-service-docker

- name: "{{ j_task }} | Create plugin folders"
  with_items:
    - /var/lib/docker-plugins/rclone/cache
    - /var/lib/docker-plugins/rclone/config
  ansible.builtin.file:
    state: directory
    dest: "{{ item  }}"

- name: "{{ j_task }} | Authenticate to GitLab"
  when: jehon_remote_gitlab_token
  become: true
  become_user: jehon-daemon
  become_method: ansible.builtin.su
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_login_module.html
  # https://docs.gitlab.com/ee/user/packages/container_registry/authenticate_with_container_registry.html
  community.docker.docker_login:
    registry_url: registry.gitlab.com
    username: "{{ jehon_remote_gitlab_username }}"
    password: "{{ jehon_remote_gitlab_token }}"
