- name: "In 90_stack > Setup stack"
  block:
    - name: "In 90_stack > Install git repo"
      become: true
      become_user: jehon-daemon
      become_method: ansible.builtin.su
      ansible.builtin.git:
        repo: "https://{{ jehon_remote_gitlab_username }}:{{ jehon_remote_gitlab_token }}@gitlab.com/{{ jh_stack_git_slug }}"
        dest: /srv/stack
        version: main
        force: true
      notify: jh_01_basis.stack_reload

    - name: "In 90_stack > Install jehon-service-stack"
      ansible.builtin.apt:
        pkg:
          - jehon-service-stack
      notify: jh_01_basis.stack_reload
