- name: Add sub-tasks
  loop_control:
    loop_var: i_file
  loop:
    - 00_variables
    - 05_update
    - 10_jehon_deb
    - 20_network
    - 50_packages
    - 70_cloud
    - 80_docker
    - 90_stack
  ansible.builtin.include_tasks:
    file: "{{ i_file }}.yml"
