- name: Add sub-tasks
  loop_control:
    loop_var: j_task
  loop: "{{ lookup('fileglob', ( role_path ~ '/tasks/[0-9]*.yml' ), wantlist=True) | map('basename') | map('regex_replace', '\\.yml', '') | sort }}"
  ansible.builtin.include_tasks:
    file: "{{ j_task }}.yml"
