---
- name: Get facts on current container
  community.docker.current_container_facts:

- name: Set is_virtual
  block:
    - name: Calculate 'virtual'
      ansible.builtin.set_fact:
        virtual: "{{ ansible_module_running_in_container }}"

    - name: Dump 'virtual'
      ansible.builtin.debug:
        var: virtual

- name: Install packages
  when: ansible_pkg_mgr == "apt"
  block:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_facts_module.html
    - name: Check packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Update system
      block:
        - name: Update cache if too old
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-cache_valid_time
          ansible.builtin.apt:
            cache_valid_time: 3600 # seconds -> 1 hour
            autoclean: true
          register: jh_01_basis_initial_apt_update
          # This does not make change!
          changed_when: false

        - name: Run upgrade
          when: jh_01_basis_initial_apt_update.cache_updated
          ansible.builtin.apt:
            upgrade: dist
          # We don't want to track those changes
          changed_when: false

############################################
#
# Imports
#
############################################
- name: Add sub-tasks
  loop_control:
    loop_var: i_file
  loop:
    - 10_jehon_deb
    - 20_network
    - 50_packages
    - 70_cloud
    - 80_docker
  ansible.builtin.include_tasks:
    file: "{{ i_file }}.yml"
