---
- name: Install package jehon-service-dev
  ansible.builtin.apt:
    pkg:
      - jehon-service-dev

- name: Setup profile
  when: dev_user is defined and dev_user
  block:
    ############################################
    #
    # User config
    #
    ############################################
    - name: Create user
      ansible.builtin.user:
        name: "{{  dev_user }}"
        shell: /usr/bin/zsh
        groups: sudo,docker,fuse,jehon_secrets
        generate_ssh_key: true
        append: true

    - name: Set password
      when: dev_password is defined and dev_password
      ansible.builtin.user:
        name: "{{ dev_user }}"
        # See https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
        update_password: on_create
        password: "{{ dev_password | password_hash('sha512', 'salt') }}"

    - name: Create restricted folder
      ansible.builtin.file:
        state: directory
        dest: /home/{{ dev_user }}/restricted/
        owner: "{{ dev_user }}"
        group: jehon_secrets
        mode: "0750"

    - name: Set git user for dev user
      when: jehon.credentials.github.display_name is defined and jehon.credentials.github.display_name
      block:
        - name: Set git user
          community.general.ini_file:
            path: /home/{{ dev_user }}/.gitconfig
            mode: "0666"
            owner: "{{ dev_user }}"
            section: user
            option: name
            value: "{{ jehon.credentials.github.display_name }}"

        - name: Include github config in general config
          community.general.ini_file:
            path: /home/{{ dev_user }}/.gitconfig
            mode: "0666"
            owner: "{{ dev_user }}"
            section: includeIf "gitdir:~/src/"
            option: path
            value: ".gitconfig-github"

        - name: Set github config for dev user
          community.general.ini_file:
            path: /home/{{ dev_user }}/.gitconfig-github
            mode: "0666"
            owner: "{{ dev_user }}"
            section: user
            option: email
            value: "{{ jehon.credentials.github.login }}@users.noreply.github.com"
