#
# - https://stackoverflow.com/a/39150040/1954789 (stdin / tty)
#

#volumes:
    # sonar_data:
    # sonar_extensions:

services:
    proxy:
        image: "traefik"
        restart: always
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            #- "81:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        labels:
            - traefik.protocol=http
            - traefik.http.middlewares.jhstriproot.stripprefixregex.regex=/[a-zA-Z0-9_-]+/

            - traefik.http.routers.api.rule=PathPrefix(`/api`)
            - traefik.http.routers.api.service=api@internal

            - traefik.http.routers.dashboard.rule=PathPrefix(`/dashboard`)
            - traefik.http.routers.dashboard.service=dashboard@internal
            - traefik.http.routers.dashboard.middlewares=jhstriproot@docker

    static:
        image: httpd:alpine
        depends_on:
            - proxy
        restart: always
        expose:
            - 80
        volumes:
            - ./httpd:/usr/local/apache2/htdocs/:ro
        labels:
            - traefik.http.routers.static.rule=PathPrefix(`/`)

    mail:
        # https://github.com/maildev/maildev
        image: maildev/maildev
        depends_on:
            - proxy
        restart: always
        environment:
            # Not working with healthcheck: - MAILDEV_BASE_PATHNAME=/maildev/
            - MAILDEV_WEB_PORT=1080
        expose:
            - 1080
            - 1025
        labels:
            # https://github.com/maildev/maildev/issues/402
            - traefik.http.routers.mail.rule=PathPrefix(`/mail`)
            - traefik.http.routers.mail.middlewares=jhstriproot@docker
            - traefik.http.services.mail.loadbalancer.server.port=1080

    jenkins:
        # Thanks to https://gist.github.com/pythoninthegrass/abb755a54ba908374e1c8bfd79d0c499
        # Image doc: https://github.com/jenkinsci/docker/blob/master/README.md
        depends_on:
            - proxy
        build:
            context: jenkins
            dockerfile: Dockerfile
        restart: always
        command: --prefix=/jenkins
        expose:
            - 8080
        healthcheck:
            test: curl -fs http://localhost:8080/jenkins/tcpSlaveAgentListener --output /dev/null
            interval: 15s
            timeout: 15s
            retries: 10
            start_period: 60s
        environment:
            PLUGINS_FORCE_UPGRADE: true
        volumes:
            - jenkins_home:/var/jenkins_home
        labels:
            - traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins`)

    jenkins_agent1:
        # Doc: https://hub.docker.com/r/jenkins/inbound-agent
        # Doc: https://hub.docker.com/r/jenkins/jnlp-slave
        # Image: https://hub.docker.com/r/jenkins/jnlp-agent-docker
        depends_on:
            jenkins:
                condition: service_healthy
            proxy:
                condition: service_started
        restart: always
        build: jenkins-agent
        # privileged: true
        environment:
            JENKINS_URL: http://jenkins:8080/jenkins/
            JENKINS_AGENT_NAME: agent1
            JENKINS_SECRET: ${JENKINS_AGENT1_TOKEN}
        volumes:
            - jenkins_agent_cache:/home/jenkins/.jenkins
            - jenkins_agent_workdir:/home/jenkins/agent
        #     - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - traefik.enable=false

volumes:
    jenkins_home:
    jenkins_agent_cache:
    jenkins_agent_workdir:
