---
- name: Get facts on current container
  community.docker.current_container_facts:

- name: Set is_virtual
  block:
    - name: Calculate 'virtual'
      ansible.builtin.set_fact:
        virtual: "{{ ansible_module_running_in_container }}"

    - name: Dump 'virtual'
      ansible.builtin.debug:
        var: virtual

- name: Install packages
  when: ansible_pkg_mgr == "apt"
  block:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_facts_module.html
    - name: Check packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Update cache if too old
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-cache_valid_time
      ansible.builtin.apt:
        cache_valid_time: 3600 # seconds -> 1 hour

    # ############################################
    # #
    # # Configure universe repository
    # #
    # ############################################

    # - name: Add ubuntu universe
    #   when: ansible_distribution == "Ubuntu"
    #   ansible.builtin.apt_repository:
    #     repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe restricted multiverse"
    #     state: present
    #     update_cache: true

    ############################################
    #
    # Install jehon.deb
    #
    ############################################

    - name: "Install jehon.deb"
      block:
        - name: Dump jh_basis_deb_url
          ansible.builtin.debug:
            var: jh_basis_deb_url

        # We need this one to be installed first, because next line will depend on it
        - name: "Install jehon.deb"
          when: "'jehon' not in ansible_facts.packages"
          ansible.builtin.apt:
            deb: "{{ jh_basis_deb_url | default('https://jehon.github.io/infrastructure/repo/jehon.deb') }}"
          notify: jh_basis.indexes
          register: jehon_basis_jehon_deb
          # Example: [run]   msg: Breaks existing package 'jehon-hardware-wsl' dependency jehon (<= 2023.06.28.14.53.03)
          failed_when: >
            jehon_basis_jehon_deb.failed
            and (
              ('A later version is already installed' != jehon_basis_jehon_deb.msg)
              and (' dependency jehon (' not in jehon_basis_jehon_deb.msg)
            )

        - name: Remove online repositories because defined jh_basis_deb_url
          when: jh_basis_deb_url is defined and jh_basis_deb_url
          ansible.builtin.file:
            path: /etc/apt/sources.list.d/jehon-github.sources
            state: absent

    ############################################
    #
    # Repositories
    #
    ############################################

    - name: Setup Debian
      when: ansible_distribution == "Debian"
      block:
        - name: Setup debian repositories
          when: jehon_debian_testing > 0
          ansible.builtin.command:
            cmd: /usr/sbin/jh-install-debian-testing {{ jehon_debian_testing }}
          register: _
          notify: jh_basis.indexes
          changed_when: "'[modified]' in _.stdout"

    - name: Refresh indexes for jehon
      ansible.builtin.meta: flush_handlers

    ############################################
    #
    # Repositories and packages
    #
    ############################################

    - name: Setup docker repository and packages
      when: jehon_repo_docker
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-docker"
      register: _
      changed_when: >
        '[modified]' in _.stdout
        or 'Preparing to unpack' in _.stdout

    - name: Setup Grafana agent repository and package
      when: grafana_api_key is defined and grafana_api_key
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-grafana-agent"
      register: _
      changed_when: "'[modified]' in _.stdout"

    - name: Setup nodejs repository and package
      # node in snap? could not access pCloudDrive... but still the best option
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-node"
      register: _
      changed_when: "'[modified]' in _.stdout"

    ############################################
    #
    # Packages jehon-*
    #
    ############################################
    - name: Install jehon-hardware-*
      block:
        - name: Calculate jehon_hardware
          block:
            - name: Set default value for jehon_hardware
              when: jehon_hardware is not defined
              ansible.builtin.set_fact:
                jehon_hardware: ""

            - name: Set jehon_hardware to wsl
              # https://stackoverflow.com/a/78046212/1954789
              when: '"microsoft" in ansible_facts["kernel"]'
              ansible.builtin.set_fact:
                jehon_hardware: wsl

            - name: Set jehon_hardware to raspberrypi
              when: ansible_architecture == "aarch64" # vs. amd64 for laptop and armv5tel for synology
              ansible.builtin.set_fact:
                jehon_hardware: raspberrypi

            - name: Set jehon_hardware to docker
              # https://docs.ansible.com/ansible/latest/collections/community/docker/current_container_facts_module.html
              when: ansible_module_running_in_container
              ansible.builtin.set_fact:
                jehon_hardware: docker

            # TODO: jehon_hardware = desktop ???

        - name: Dump jehon_hardware
          ansible.builtin.debug:
            var: jehon_hardware

        - name: Install hardware package
          when: jehon_hardware | length > 0
          block:
            - name: "Ensure jehon-hardware is present for hardware {{ jehon_hardware }}"
              ansible.builtin.apt:
                pkg:
                  - "jehon-hardware-{{ jehon_hardware }}"
