---
- name: Install packages
  when: ansible_pkg_mgr == "apt"
  block:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_facts_module.html
    - name: Check packages
      ansible.builtin.package_facts:
        manager: auto

    ############################################
    #
    # Jehon.deb
    #
    ############################################

    # We need this one to be installed first, because next line will depend on it
    - name: "Install jehon.deb from {{ jh_basis_deb_url }}"
      when: "'jehon' not in ansible_facts.packages"
      ansible.builtin.apt:
        deb: "{{ jh_basis_deb_url | default('https://jehon.github.io/infrastructure/repo/jehon.deb') }}"
      notify: jh_basis.indexes
      register: jehon_basis_jehon_deb
      # Example: [run]   msg: Breaks existing package 'jehon-hardware-wsl' dependency jehon (<= 2023.06.28.14.53.03)
      failed_when: >
        jehon_basis_jehon_deb.failed
        and (
          ('A later version is already installed' != jehon_basis_jehon_deb.msg)
          and (' dependency jehon (' not in jehon_basis_jehon_deb.msg)
        )

    - name: "Remove online repositories because defined {{ jh_basis_deb_url }}"
      when: jh_basis_deb_url is defined
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/jehon-github.sources
        state: absent

    ############################################
    #
    # Tools
    #
    ############################################

    ############################################
    #
    # Repositories
    #
    ############################################

    - name: Setup Debian
      when: ansible_distribution == "Debian"
      block:
        - name: Setup debian repositories
          when: jehon_testing > 0
          ansible.builtin.command:
            cmd: "/usr/sbin/jh-install-debian-testing {{ jehon_testing }}"
          register: result
          notify: jh_basis.indexes
          changed_when: "'[modified]' in result.stdout"

    - name: Refresh indexes for jehon
      ansible.builtin.meta: flush_handlers

    ############################################
    #
    # Repositories and packages
    #
    ############################################

    - name: Setup docker repository and packages
      when: jehon_repo_docker
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-docker"
      register: result
      changed_when: >
        '[modified]' in result.stdout
        or 'Preparing to unpack' in result.stdout

    - name: Setup Grafana agent repository and package
      when: grafana_api_key is defined and 'grafana-agent' not in ansible_facts.packages
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-grafana-agent"
      changed_when: true

    - name: Setup nodejs repository and package
      when: nodejs is defined
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-node"
      register: result
      changed_when: "'[modified]' in result.stdout"

    ############################################
    #
    # Packages
    #
    ############################################
    - name: Set default value for jehon_hardware
      when: jehon_hardware is not defined
      ansible.builtin.set_fact:
        jehon_hardware: ""

    - name: Set jehon_hardware to wsl
      # https://stackoverflow.com/a/78046212/1954789
      when: '"microsoft" in ansible_facts["kernel"]'
      ansible.builtin.set_fact:
        jehon_hardware: wsl

    # TODO: auto detect raspberrypi
    # - name: Set jehon_hardware to raspberrypi
    #   when: ??
    #   ansible.builtin.set_fact:
    #     jehon_hardware: raspberrypi

    # TODO: auto detect docker
    # - name: Set jehon_hardware to docker
    #   when: ??
    #   ansible.builtin.set_fact:
    #     jehon_hardware: docker

    - name: Install hardware package - jehon-hardware-*
      when: jehon_hardware | length > 0
      block:
        - name: "Ensure jehon-hardware is present for hardware {{ jehon_hardware }}"
          ansible.builtin.apt:
            pkg:
              - "jehon-hardware-{{ jehon_hardware }}"
