services:
  index:
    image: httpd:alpine
    # https://hub.docker.com/_/httpd
    restart: always
    expose:
      - 80
      - 443
    ports:
      # - "80:80"
      - target: 80
        published: 5080
        mode: host
    volumes:
      - type: bind
        source: index
        target: /usr/local/apache2/htdocs/

  torrent:
    image: linuxserver/transmission
    # https://hub.docker.com/r/linuxserver/transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $HOME/data/torrent/data:/config
      - $HOME/data/torrent/downloads:/downloads
      - $HOME/data/torrent/watch:/watch
    ports:
      - 9091:9091 # Web UI
      # - 51413:51413 # Torrent traffic
      # - 51413:51413/udp # Torrent traffic

  gitlab:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: $HOME/data/gitlab
        target: /etc/gitlab-runner
