services:
  index:
    image: httpd:alpine
    # https://hub.docker.com/_/httpd
    restart: always
    expose:
      - 80
      - 443
    ports:
      # - "80:80"
      - target: 80
        published: 5080
        mode: host
    volumes:
      - type: bind
        source: index
        target: /usr/local/apache2/htdocs/

  torrent:
    image: linuxserver/transmission
    # https://hub.docker.com/r/linuxserver/transmission
    restart: always
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  gitlab:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: $HOME/data/gitlab
        target: /etc/gitlab-runner
