---
- name: Install package jehon-service-dev
  ansible.builtin.apt:
    pkg:
      - jehon-service-dev

- name: Setup profile
  block:
    - name: Add user jehon
      ansible.builtin.include_role:
        name: user_jehon
      vars:
        user: jehon
        display_name: Jean Honlet
        github_login: jehon

- name: Setup google-chrome repository and packages
  when: "'google-chrome-stable' not in ansible_facts.packages"
  ansible.builtin.command:
    cmd: "/usr/sbin/jh-install-google-chrome"
  changed_when: true
