---
- name: Install package jehon-service-dev
  ansible.builtin.apt:
    pkg:
      - jehon-service-dev

- name: Setup profile
  when: dev_user | length > 0
  block:
    ############################################
    #
    # User config
    #
    ############################################
    - name: Create user
      ansible.builtin.user:
        name: "{{  dev_user }}"
        # TODO: zsh shell
        shell: /bin/bash
        groups: sudo,docker,fuse,jehon_secrets
        generate_ssh_key: true
        append: true

    - name: Set password
      when: dev_password | default("") | length > 0
      ansible.builtin.user:
        name: "{{ dev_user }}"
        # See https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
        update_password: on_create
        password: "{{ dev_password | password_hash('sha512', 'salt') }}"

    - name: Create restricted folder
      ansible.builtin.file:
        state: directory
        dest: /home/{{ dev_user }}/restricted/
        owner: "{{ dev_user }}"
        group: jehon_secrets
        mode: "0750"

    - name: Install secrets files for {{ dev_user }}
      with_items:
        - cryptomedic.php
        - cryptomedic.sh
        - dev.sh
        - jenkins.env
        - jenkins-master.key
        - koalty.sh
        - tmdb.key
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/home/{{ dev_user }}/restricted/{{ item }}"
        owner: "{{ dev_user }}"
        group: jehon_secrets
        mode: "0700"

    - name: Set git user for {{ "'" + dev_user + "-" + jehon.github.display_name + "'" }}
      community.general.ini_file:
        path: /home/{{ dev_user }}/.gitconfig
        mode: "0666"
        owner: "{{ dev_user }}"
        section: user
        option: name
        value: "{{ jehon.github.display_name }}"

    - name: Include github config in general config
      community.general.ini_file:
        path: /home/{{ dev_user }}/.gitconfig
        mode: "0666"
        owner: "{{ user }}"
        section: includeIf "gitdir:~/src/"
        option: path
        value: ".gitconfig-github"

    - name: Set github config for {{ "'" + dev_user + " - " + jehon.github.login + "'" }}
      community.general.ini_file:
        path: /home/{{ dev_user }}/.gitconfig-github
        mode: "0666"
        owner: "{{ dev_user }}"
        section: user
        option: email
        value: "{{ jehon.github.login }}@users.noreply.github.com"

    - name: Local SSH Config
      ansible.builtin.template:
        src: "{{ role_path }}/templates/ssh_config"
        dest: /home/{{ dev_user }}/.ssh/config
        owner: "{{ dev_user }}"
        group: "jehon_secrets"
        mode: "0640"

    # - name: Run as user
    #   become: true
    #   become_user: "{{ dev_user }}"
    #   block:
    # TODO: reactivate docker rootless (not working on wsl)
    #     - name: Docker rootless
    #       ansible.builtin.command:
    #         cmd: /usr/bin/dockerd-rootless-setuptool.sh install
    #       register: _
    #       changed_when: '"File already exists" not in _.stdout'
    #
    # - name: Docker - login to docker hub
    #   when: jehon.docker.username | length > 0 and jehon.docker.token | length > 0
    #   ansible.builtin.command:
    #     cmd: echo "{{ jehon.docker.token }}" | docker login -u "{{ jehon.docker.username }}"
    #   changed_when: true
