---
- name: Setup dev profile
  when: jehon_dev_user is defined and jehon_dev_user
  block:
    ############################################
    #
    # User config
    #
    ############################################
    - name: Install secrets files for dev for {{ jehon_dev_user }}
      with_items:
        - cryptomedic.php
        - cryptomedic.sh
        - dev.sh
        - koalty.sh
        - tmdb.key
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/home/{{ jehon_dev_user }}/restricted/{{ item }}"
        owner: "{{ jehon_dev_user }}"
        group: jehon-secrets
        mode: "0700"

    # - name: Run as user
    #   become: true
    #   become_user: "{{ jehon_dev_user }}"
    #   block:
    #     - name: Docker rootless
    #       when: not virtual
    #       ansible.builtin.command:
    #         cmd: /usr/bin/dockerd-rootless-setuptool.sh install --force
    #       register: _
    #       changed_when: '"CLI context \"rootless\" already exists" not in _.stdout'

    # - name: Docker - login to docker hub
    #   when: jehon_remote_docker_token | length > 0 and jehon_remote_docker_token | length > 0
    #   ansible.builtin.command:
    #     cmd: echo "{{ jehon_remote_docker_token }}" | docker login -u "{{ jehon_remote_docker_username }}"
    #   changed_when: false

#
# Desktop side
#
- name: Setup desktop environment
  block:
    - name: Install desktop packages
      ansible.builtin.apt:
        pkg:
          - jehon-service-desktop
          - ffmpegthumbnailer # Thumbnails for movies
          # - gnome-network-displays
          # - gnome-shell-extensions
          # - gthumb # Print multiple images on one page
          - libfuse2 # pcloud

    - name: "Ensure installed snap"
      when: not virtual
      with_items:
        - firefox
        - digikam
        - gimp
        - ksnip
        - mkvtoolnix-jz
        - libreoffice
        - slack
        - spotify
        - whatsapp-for-linux # Personnal (conf call)
        - vlc
      community.general.snap:
        name: "{{ item }}"
        state: present

    - name: "Ensure installed snap (classic)"
      when: not virtual
      with_items:
        - code
      community.general.snap:
        name: "{{ item }}"
        state: present
        classic: true

    - name: "Ensure installed snap (special) "
      when: not virtual
      with_items:
        - subtitle-edit
      community.general.snap:
        name: "{{ item }}"
        state: present
        channel: edge

- name: Setup client1
  ansible.builtin.include_role:
    name: client_1
