---
- name: Setup dev profile
  when: dev_user is defined and dev_user
  block:
    ############################################
    #
    # User config
    #
    ############################################
    - name: Install secrets files for dev for {{ dev_user }}
      with_items:
        - cryptomedic.php
        - cryptomedic.sh
        - dev.sh
        - jenkins.env
        - jenkins-master.key
        - koalty.sh
        - tmdb.key
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/home/{{ dev_user }}/restricted/{{ item }}"
        owner: "{{ dev_user }}"
        group: jehon_secrets
        mode: "0700"

    - name: Local SSH Config for dev
      ansible.builtin.template:
        src: "{{ role_path }}/templates/ssh_config"
        dest: /home/{{ dev_user }}/.ssh/config
        owner: "{{ dev_user }}"
        group: "jehon_secrets"
        mode: "0640"

    - name: Run as user
      become: true
      become_user: "{{ dev_user }}"
      block:
        - name: Docker rootless
          ansible.builtin.command:
            cmd: /usr/bin/dockerd-rootless-setuptool.sh install --force
          register: _
          changed_when: '"CLI context \"rootless\" already exists" not in _.stdout'

    # - name: Docker - login to docker hub
    #   when: jehon.docker.username | length > 0 and jehon.docker.token | length > 0
    #   ansible.builtin.command:
    #     cmd: echo "{{ jehon.docker.token }}" | docker login -u "{{ jehon.docker.username }}"
    #   changed_when: false
