---
- name: Install package jehon-service-dev
  ansible.builtin.apt:
    pkg:
      - jehon-service-dev

- name: Setup profile
  when: dev_user | length > 0
  block:
    ############################################
    #
    # User config
    #
    ############################################
    - name: Create restricted folder
      ansible.builtin.file:
        state: directory
        dest: /home/{{ dev_user }}/restricted/
        owner: "{{ dev_user }}"
        group: jehon_secrets
        mode: "0750"

    - name: Install secrets files for {{ dev_user }}
      with_items:
        - cryptomedic.php
        - cryptomedic.sh
        - dev.sh
        - jenkins.env
        - jenkins-master.key
        - koalty.sh
        - tmdb.key
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/home/{{ dev_user }}/restricted/{{ item }}"
        owner: "{{ dev_user }}"
        group: jehon_secrets
        mode: "0700"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/getent_module.html
    - name: Get users
      ansible.builtin.getent:
        database: passwd

    - name: Add to system groups user {{ dev_user }}
      ansible.builtin.user:
        name: "{{ dev_user }}"
        comment: "{{ jehon.github.display_name }}"
        groups: sudo,docker,fuse,jehon_secrets
        append: true
        generate_ssh_key: true

    - name: Set password
      when: dev_password | length > 0
      ansible.builtin.user:
        name: "{{ dev_user }}"
        # See https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
        password: "{{ dev_password | password_hash('sha512', 'salt') }}"

    - name: Set git user for {{ "'" + dev_user + "-" + jehon.github.display_name + "'" }}
      community.general.ini_file:
        path: /home/{{ dev_user }}/.gitconfig
        mode: "0666"
        owner: "{{ dev_user }}"
        section: user
        option: name
        value: "{{ jehon.github.display_name }}"

    - name: Include github config in general config
      community.general.ini_file:
        path: /home/{{ dev_user }}/.gitconfig
        mode: "0666"
        owner: "{{ user }}"
        section: includeIf "gitdir:~/src/"
        option: path
        value: ".gitconfig-github"

    - name: Set github config for {{ "'" + dev_user + " - " + jehon.github.login + "'" }}
      community.general.ini_file:
        path: /home/{{ dev_user }}/.gitconfig-github
        mode: "0666"
        owner: "{{ dev_user }}"
        section: user
        option: email
        value: "{{ jehon.github.login }}@users.noreply.github.com"

    - name: Local SSH Config
      ansible.builtin.template:
        src: "{{ role_path }}/templates/ssh_config"
        dest: /home/{{ dev_user }}/.ssh/config
        owner: "{{ dev_user }}"
        group: "jehon_secrets"
        mode: "0640"
