---
- name: Setup Gitlab runner
  block:
    - name: Install Gitlab runner packages
      ansible.builtin.apt:
        pkg:
          - gitlab-runner
      notify: jh_gitlab_runner.gitlab-runner

- name: Configure rights
  block:
    - name: Add gitlab-runner to docker group
      ansible.builtin.user:
        name: gitlab-runner
        groups:
          - docker
        append: true
      notify: jh_gitlab_runner.gitlab-runner
    - name: Configure rights on folder
      ansible.builtin.file:
        state: directory
        path: /etc/gitlab-runner
        owner: root
        group: jehon-secrets
        mode: "0775"
    - name: Configure rights on config
      ansible.builtin.file:
        state: file
        path: /etc/gitlab-runner/config.toml
        owner: root
        group: jehon-secrets
        mode: "0775"
    #
    # - name: Fix config
    #   block:
    #     - name: Enable privileged mode
    #       ansible.builtin.lineinfile:
    #         path: /etc/gitlab-runner/config.toml
    #         regexp: "^[ ]+privileged[ ]*="
    #         line: privileged = true
    #       notify: jh_gitlab_runner.gitlab-runner
    #     - name: Fix image for runner
    #       ansible.builtin.lineinfile:
    #         path: /etc/gitlab-runner/config.toml
    #         regexp: "^[ ]+image[ ]*="
    #         line: 'image = "docker"'
    #       notify: jh_gitlab_runner.gitlab-runner
