---

# https://storage.googleapis.com/cloud-onboarding/agent/config/config.yamlintegrations:

integrations:
  prometheus_remote_write:
  - basic_auth:
      username: {{ grafana_tenant_id }}
      password: {{ grafana_api_key }}
    url: {{ grafana_integrations_url }}
  agent:
    enabled: true
    relabel_configs:
    - action: replace
      source_labels:
      - agent_hostname
      target_label: instance
    - action: replace
      target_label: job
      replacement: "integrations/agent-check"
    metric_relabel_configs:
    - action: keep
      regex: (prometheus_target_sync_length_seconds_sum|prometheus_target_scrapes_.*|prometheus_target_interval.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
      source_labels:
      - __name__
  # integrations section
logs:
  configs:
  - clients:
    - basic_auth:
        username: {{ grafana_logs_id }}
        password: {{ grafana_api_key }}
      url: {{ grafana_logs_url }}
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      # logs.configs.scrape_configs section
metrics:
  configs:
  - name: integrations
    remote_write:
    - basic_auth:
        username: {{ grafana_tenant_id }}
        password: {{ grafana_api_key }}
      url: {{ grafana_metrics_url }}
    scrape_configs:
      # metrics.configs.scrape_configs section
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
