---

- name: Update dependencies kiosk
  listen: host_kiosk.restart-kiosk
  ansible.builtin.command:
    chdir: /opt/jehon/kiosk
    cmd: /usr/bin/jh-npm-update-if-necessary
  register: host_kiosk_handler_update
  changed_when: "'Updating' in host_kiosk_handler_update.stdout"

- name: Restart kiosk
  when: not virtual
  listen: host_kiosk.restart-kiosk
  ansible.builtin.systemd:
    name: jehon-kiosk
    state: restarted
