#!/usr/bin/env bash

set -o errexit

# shellcheck source-path=SCRIPTDIR/
. "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../conf-lib.sh"

##################################
#
# Config
#

target="${jhCloudFolderInUserHome}/Workspaces/Famille/A ranger/"

##################################
#
# Requirements
#

# shellcheck source-path=SCRIPTDIR/../../
"${prjRoot}"/bin/jh-wait-folder "${target}"

# shellcheck source-path=SCRIPTDIR/../../
"${prjRoot}"/bin/jh-location-exclude "mobile"

##################################
#
# Run
#

user_report_failure

jh_value "CLOUD" "${jhCloudFolderInUserHome}"
jh_value "TARGET" "${target}"

if [ ! -d "${target}" ]; then
    echo "Could not access target ${target}... exiting"
    exit 0
fi

import() {
    name="$1"
    source="${jhCloudFolderInUserHome}/$1"
    shift

    jh_info "Importing $name"
    if [ ! -d "${source}" ]; then
        jh_fatal "Could not read source ${source}"
    fi

    # FIXME: rework TZ into fo.ts and remove harmony-temporal
    export TZ="Europe/Brussels"
    jh-fo "import" --no-progress --to "${target}" "${source}"
}

import "Workspaces/Jean/Backups/Google Pixel 7 Pro/"
import "Workspaces/Marie-Line/Automatic Upload/"

ok "Done"
