#!/usr/bin/env bash

set -o errexit

_SD="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source-path=SCRIPTDIR/
. "${_SD}/../../bin/lib.sh"

# shellcheck source-path=SCRIPTDIR/../../
. "${prjRoot}"/bin/jh-run-only-daily

target="${jhCloudFolderInUserHome}/Workspaces/Famille/A ranger/"

jh_value "CLOUD" "${jhCloudFolderInUserHome}"
jh_value "TARGET" "${target}"

# shellcheck source-path=SCRIPTDIR/../../
"${prjRoot}"/bin/jh-wait-home-cloud "${target}"

if [ ! -d "${target}" ]; then
    echo "Could not access target ${target}... exiting"
    exit 0
fi

user_report_failure

import() {
    name="$1"
    source="${jhCloudFolderInUserHome}/$1"
    shift

    jh_info "Importing $name"
    if [ ! -d "${source}" ]; then
        jh_fatal "Could not read source ${source}"
    fi

    # FIXME: rework TZ into fo.ts and remove harmony-temporal
    export TZ="Europe/Brussels"
    jh-fo "import" --no-progress --to "${target}" "${source}"
}

import "Workspaces/Jean/Automatic Upload J/"
import "Workspaces/Marie-Line/Automatic Upload/"

ok "Done"
