---
- name: Install packages
  when: ansible_pkg_mgr == "apt"
  block:
    - name: Install jehon.deb
      block:
        # We need this one to be installed first, because next line will depend on it
        - name: "Install jehon.deb from the web"
          ansible.builtin.apt:
            deb: "https://jehon.github.io/packages/jehon.deb"
          notify: jh_basis.indexes
          register: jehon_basis_jehon_deb
          # Example: [run]   msg: Breaks existing package 'jehon-hardware-wsl' dependency jehon (<= 2023.06.28.14.53.03)
          failed_when: >
            jehon_basis_jehon_deb.failed
            and (
              ('A later version is already installed' != jehon_basis_jehon_deb.msg)
              and (' dependency jehon (' not in jehon_basis_jehon_deb.msg)
            )

        - name: Refresh indexes for jehon
          ansible.builtin.meta: flush_handlers

    - name: Install jehon-hardware*.deb
      when: jehon_hardware | length > 0
      block:
        - name: "Ensure jehon-hardware is present for hardware {{ jehon_hardware }}"
          ansible.builtin.apt:
            pkg:
              - "jehon-hardware-{{ jehon_hardware }}"

    - name: "Ensure jehon-service-headless is present"
      when: jehon_headless
      ansible.builtin.apt:
        pkg:
          - "jehon-service-headless"

- name: In full machine
  when: not virtual
  block:
    - name: Set default tty
      when: jehon_tty | int > 0
      ansible.builtin.systemd:
        name: jehon-chvt@{{ jehon_tty }}.service
        enabled: true
        state: started
