---

#
# User side
#
- name: Setup profile
  block:
    - name: Add user jehon
      ansible.builtin.include_role:
        name: jehon_service_dev
      vars:
        user: jehon
        display_name: Jean Honlet
        github_login: jehon

- name: Install desktop packages
  ansible.builtin.apt:
    pkg:
      - copyq
      - digikam
      - gnome-network-displays
      - gnome-shell-extensions

- name: "Ensure installed snap (classic)"
  when: not virtual
  with_items:
    - gimp
    - ksnip
    - mkvtoolnix-jz
    - node
    - shellcheck
    - snap-store
    - vlc
    - youtube-dl
  community.general.snap:
    name: "{{ item }}"
    state: present

- name: "Ensure installed snap (edge)"
  when: not virtual
  with_items:
    - firefox
    - youtube-dl
  community.general.snap:
    name: "{{ item }}"
    state: present
