---

#
# User side
#
- name: Setup profile
  block:
    - name: Add user jehon
      ansible.builtin.include_role:
        name: jehon_service_dev
      vars:
        user: jehon
        display_name: Jean Honlet
        github_login: jehon
