---

- name: Setup dev system
  block:
    - name: Setup debian repositories
      ansible.builtin.command:
        command: "/usr/sbin/jh-install-debian-testing"
      register: host_dev_debian
      changed_when: "'[Change]' in host_dev_debian.stdout"

      # TODO

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - jehon-service-dev
          - jehon-service-music-refresh
          # Docker
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: Create links
      ansible.builtin.file:
        # pointing to
        src: /usr/bin/dockerd
        # link name
        dest: /usr/sbin/dockerd
        state: link

#
# User/dev files
#
- name: Setup system-wide files for user
  block:
    - name: Install secrets files
      with_items:
        - cryptomedic.php
        - cryptomedic.sh
        - dev.sh
        - jenkins-master.key
        - jenkins.env
        - tmdb.key
      ansible.builtin.template:
        src: "{{ item }}"
        dest: /etc/jehon/restricted/{{ item }}
        owner: root
        group: jehon_secrets
        mode: "0750"

#
# User side
#
- name: Setup profile
  block:
    - name: Add user jehon
      ansible.builtin.include_role:
        name: jh_user_dev
      vars:
        user: jehon
