---

- name: Setup dev system
  block:
    - name: Setup debian repositories
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-debian-testing"
      register: host_dev_debian
      changed_when: "'[Change]' in host_dev_debian.stdout"
      notify: host_dev.repositories

    - name: Setup docker repository
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-docker"
      register: host_dev_docker
      # TODO: detect changes
      changed_when: true

#
# User side
#
- name: Setup profile
  block:
    - name: Add user jehon
      ansible.builtin.include_role:
        name: jehon_service_dev
      vars:
        user: jehon
