---

- name: Setup dev system
  block:
    - name: Setup debian repositories
      ansible.builtin.template:
        src: jehon-debian.sources
        dest: /etc/apt/sources.list.d/
        mode: "0644"

    - name: Setup debian preferences
      ansible.builtin.template:
        src: 10-jehon-debian.pref
        dest: /etc/apt/preferences.d/
        mode: "0644"

    - name: Remove packages
      ansible.builtin.apt:
        state: absent
        pkg:
          # Docker
          - docker.io

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - jehon-desktop
          - jehon-service-music-refresh
          # Docker
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: Create links
      ansible.builtin.file:
        # pointing to
        src: /usr/bin/dockerd
        # link name
        dest: /usr/sbin/dockerd
        owner: foo
        group: foo
        state: link

#
# User/dev files
#
- name: Setup system-wide files for user
  block:
    - name: Set docker shared folder
      ansible.builtin.file:
        path: /mnt/docker
        state: directory
        mode: "0775"
        group: jh_secrets

    - name: Install secrets files
      with_items:
        - cryptomedic.php
        - cryptomedic.sh
        - dev.sh
        - jenkins-master.key
        - jenkins.env
        - tmdb.key
      ansible.builtin.template:
        src: "{{ item }}"
        dest: /etc/jehon/restricted/{{ item }}
        owner: root
        group: jh_secrets
        mode: "0750"

    - name: Install /mnt/docker/jenkins
      ansible.builtin.file:
        state: directory
        dest: /mnt/docker/jenkins
        owner: root
        group: jh_secrets
        mode: "0755"

    - name: Enable photo mount
      when: not virtual
      ansible.builtin.systemd:
        name: mnt-cloud-photos.mount
        enabled: true
        state: started

#
# User side
#
- name: Setup profile
  block:
    - name: Add user jehon
      ansible.builtin.include_role:
        name: jh_user_dev
      vars:
        user: jehon
