---

#
# User side
#
- name: Setup profile
  block:
    - name: Add user jehon
      ansible.builtin.include_role:
        name: jehon_service_dev
      vars:
        user: jehon
        display_name: Jean Honlet
        github_login: jehon

- name: Install desktop packages
  ansible.builtin.apt:
    pkg:
      - copyq
      - digikam
      - git-flow
      - gnome-network-displays
      - gnome-shell-extensions
      - libfuse2                # pcloud

- name: "Ensure installed snap (classic)"
  when: not virtual
  with_items:
    - gimp
    - ksnip
    - mkvtoolnix-jz
    - shellcheck
    - snap-store
    - vlc
    - youtube-dl-pro
  community.general.snap:
    name: "{{ item }}"
    state: present
# node in snap? could not access pCloudDrive...

- name: "Ensure installed snap (edge)"
  when: not virtual
  with_items:
    - firefox
  community.general.snap:
    name: "{{ item }}"
    state: present

- name: Setup google-chrome repository and packages
  when: jehon_repo_docker
  ansible.builtin.command:
    cmd: "/usr/sbin/jh-install-google-chrome"
  register: result
  changed_when: >
    '[change]' in result.stdout
    or 'Preparing to unpack' in result.stdout
