---

- name: Setup dev system
  block:
    - name: Setup debian repositories
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-debian-testing"
      register: result
      changed_when: "'[change]' in result.stdout"
      notify: host_dev.repositories

#
# User side
#
- name: Setup profile
  block:
    - name: Add user jehon
      ansible.builtin.include_role:
        name: jehon_service_dev
      vars:
        user: jehon
