# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "alvistack/debian-testing"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # TODO: map config
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive

    apt-get update
    apt install --quiet --yes

    # TODO: install jehon blablabla
    apt-get install -y docker
    systemctl enable --now docker.service

    # See docker group problem
  SHELL
end
