---
- name: Install kiosk packages
  ansible.builtin.apt:
    pkg:
      - jehon-service-music
      - jehon-service-kiosk
      - jehon-service-headless

- name: "Set a hostname to {{ inventory_hostname }}"
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: not virtual
