---
- name: Configure cloud
  when: cloud_type | length > 0
  block:
    - name: Install packages (fuse)
      when: ansible_pkg_mgr == "apt"
      ansible.builtin.apt:
        name:
          - fuse3
      notify: Jh_cloud.remount

    - name: "Install config"
      ansible.builtin.template:
        src: "rclone.conf"
        dest: /etc/jehon/rclone.conf
        owner: root
        group: jehon-secrets
        mode: "0640"
      notify: Jh_cloud.remount

    - name: Enable cloud mount service
      when: not virtual
      with_items: "{{ mount_list }}"
      ansible.builtin.systemd:
        name: jehon-cloud@{{ item }}.service
        enabled: "{{ jh_cloud_start }}"
        state: "{{ 'started' if jh_cloud_start else 'stopped' }}"

## ELSE ##
- name: "Remove config"
  when: cloud_type | length == 0
  ansible.builtin.file:
    dest: /etc/jehon/rclone.conf
    state: absent
  notify: Jh_cloud.systemctl_reload
