---
- name: Configure cloud
  when: jehon_cloud_type | length > 0
  block:
    - name: Install packages (fuse)
      when: ansible_pkg_mgr == "apt"
      ansible.builtin.apt:
        name:
          - fuse3

    - name: "Install config"
      ansible.builtin.template:
        src: "rclone.conf"
        dest: /etc/jehon/rclone.conf
        owner: root
        group: jehon-daemon
        mode: "0640"

    # - name: Enable cloud mount service
    #   when: not virtual
    #   with_items: "{{ mount_list }}"
    #   ansible.builtin.systemd:
    #     name: jehon-cloud@{{ item }}.service
    #     enabled: "{{ jh_cloud_start }}"
    #     state: "{{ 'started' if jh_cloud_start else 'stopped' }}"

## ELSE ##
- name: "Remove config"
  when: jehon_cloud_type | length == 0
  ansible.builtin.file:
    dest: /etc/jehon/rclone.conf
    state: absent
  notify: Jh_cloud.systemctl_reload
#
# TODO: enable various mounts
#
