---
- name: Restart gitlab-runner
  listen: jh_gitlab_runner.gitlab-runner
  when: not virtual
  ansible.builtin.systemd:
    daemon_reload: true
    name: gitlab-runner.service
    state: restarted
  changed_when: false
