- name: Dump variables
  hosts: all
  gather_facts: false

  tasks:
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

    - name: Display facts
      ansible.builtin.debug:
        var: ansible_facts
