---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

#
# We need to pass through all this for handlers to run only once
#

- name: Setup systems
  hosts: all
  tasks:
    - name: Setup jh_01_basis
      when: "'grp_jehon' in group_names"
      ansible.builtin.include_role:
        name: jh_01_basis

    - name: Setup host dev
      when: inventory_hostname == "dev"
      loop:
        - host_dev
      loop_control:
        loop_var: include_role
      ansible.builtin.include_role:
        name: "{{ include_role }}"

    - name: Setup host kiosk
      when: inventory_hostname == "kiosk"
      loop:
        - host_kiosk
      loop_control:
        loop_var: include_role
      ansible.builtin.include_role:
        name: "{{ include_role }}"

    - name: Setup host vps
      when: inventory_hostname == "vps"
      loop:
        - host_vps
      loop_control:
        loop_var: include_role
      ansible.builtin.include_role:
        name: "{{ include_role }}"
