---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

#
# We need to pass through all this for handlers to run only once
#

- name: Setup systems
  hosts: all
  tasks:
    - name: Setup jh_basis
      when: "'grp_jehon' in group_names"
      ansible.builtin.include_role:
        name: jh_basis

    - name: Setup networking
      when: "'grp_jehon' in group_names"
      ansible.builtin.include_role:
        name: jh_network

    - name: Setup cloud
      when: "'grp_jehon' in group_names"
      ansible.builtin.include_role:
        name: jh_cloud

    - name: Setup host dev
      when: inventory_hostname == "dev"
      with_items:
        - host_dev
        - jh_gitlab_runner
        - client_1
      loop_control:
        loop_var: role
      ansible.builtin.include_role:
        name: "{{ role }}"

    - name: Setup host kiosk
      when: inventory_hostname == "kiosk"
      ansible.builtin.include_role:
        name: host_kiosk

    - name: Setup host vps
      when: inventory_hostname == "vps"
      with_items:
        - host_vps
        - jh_gitlab_runner

      loop_control:
        loop_var: role
      ansible.builtin.include_role:
        name: "{{ role }}"
