---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

#
# We need to pass through all this for handlers to run only once
#

- name: Setup systems
  hosts: computers
  tasks:
    - name: Setup jh_01_basis
      ansible.builtin.include_role:
        name: jh_01_basis

    - name: Setup host
      ansible.builtin.include_role:
        name: "host_{{ inventory_hostname }}"

- name: Generate artifacts
  hosts: artifacts
  tasks:
    - name: Generate dev-config.yml for github homepage
      loop:
        - dev-config.json
        - user-data
      ansible.builtin.template:
        src: "templates/{{ item }}"
        dest: "../tmp/publish/{{ item }}"
        mode: "0644"
