---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

#
# We need to pass through all this for handlers to run only once
#

- name: Setup systems
  hosts: all
  tasks:
    - name: Setup jh_basis
      when: "'grp_jehon' in group_names"
      ansible.builtin.include_role:
        name: jh_basis

    - name: Setup host dev
      when: inventory_hostname == "dev"
      ansible.builtin.include_role:
        name: "{{  item }}"
      with_items:
        - jh_network
        - jh_cloud
        - host_dev

    - name: Setup host kiosk
      when: inventory_hostname == "kiosk"
      ansible.builtin.include_role:
        name: "{{  item }}"
      with_items:
        - jh_network
        - jh_cloud
        - host_kiosk

    - name: Setup host vps
      when: inventory_hostname == "vps"
      ansible.builtin.include_role:
        name: "{{  item }}"
      with_items:
        - jh_network
        - jh_cloud
        - host_vps
