---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

#
# We need to pass through all this for handlers to run only once
#

- name: Setup systems
  hosts: computers
  tasks:
    - name: Setup jh_01_basis
      ansible.builtin.include_role:
        name: jh_01_basis

    - name: Setup host
      ansible.builtin.include_role:
        name: "host_{{ inventory_hostname }}"

- name: Generate artifacts
  hosts: artifacts
  tasks:
    - name: Build artifacts
      ansible.builtin.include_role:
        name: artifacts
