---
- name: Setup systems
  hosts: grp_jehon
  tasks:
    - name: Do a full upgrade and reboot
      ansible.builtin.command:
        cmd: /usr/sbin/jehon-system-upgrade full
      changed_when: false
