services:
  index:
    image: httpd:alpine
    # https://hub.docker.com/_/httpd
    restart: always
    expose:
      - 80
      - 443
    ports:
      # - "80:80"
      - target: 80
        published: 80
        mode: host
    volumes:
      - type: bind
        source: index
        target: /usr/local/apache2/htdocs/

  torrent:
    image: linuxserver/transmission
    # https://hub.docker.com/r/linuxserver/transmission
    restart: always
    # ports:
    #   - ""
