services:
  test:
    image: httpd:alpine
    # https://hub.docker.com/_/httpd
    restart: always
    expose:
      - 80
      - 443
    ports:
      - "80:80"
    healthcheck:
      test: wget -O - http://127.0.0.1:1080/healthz
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 3s
