---

#
# Detect interface?
#
#   https://serverfault.com/a/948288/275843
#
# !! change are applied only after reboot
#

- name: Setup Lan
  when: jehon_ip | length > 0
  block:
    - name: Deploy the netplan
      ansible.builtin.template:
        src: netplan-fixed.yaml
        dest: /etc/netplan/eth0-fixed.yaml
        mode: "0644"
      notify: jh_network.changed
