---

#
# Detect interface?
#
#   https://serverfault.com/a/948288/275843
#
# !! change are applied only after reboot
#

- name: Setup Lan
  # We can do this anyway, since the systemctl will be done only in not-virtual
  when: jehon_ip | length > 0
  block:
    - name: Deploy the netplan
      ansible.builtin.template:
        src: netplan-fixed.yaml
        dest: /etc/netplan/eth0-fixed.yaml
        mode: "0644"
      notify: jh_network.changed

- name: Set a hostname to {{ inventory_hostname }}
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: not virtual and inventory_hostname is match("[a-zA-Z][a-zA-Z0-9_-]+") and inventory_hostname != "localhost"

- name: Firewall - allow ssh
  when: not virtual
  community.general.ufw:
    rule: allow
    name: ssh

- name: Firewall - enable
  when: not virtual
  community.general.ufw:
    state: enabled
