#!/usr/bin/env bash

set -o errexit

_SD="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source-path=SCRIPTDIR/
. "${_SD}/../../../bin/lib.sh"

PCLOUD="${HOME}/pCloudDrive"
TARGET="${PCLOUD}/Workspaces/Famille/A ranger/"

jh_value "PCLOUD" "${PCLOUD}"
jh_value "TARGET" "${TARGET}"

if [ ! -d "${TARGET}" ]; then
    echo "Could not access target ${TARGET}... exiting"
    exit 0
fi

import() {
    NAME="$1"
    SOURCE="${PCLOUD}/$1"
    shift

    jh_info "Importing $NAME"
    if [ ! -d "${SOURCE}" ]; then
        jh_fatal "Could not read source ${SOURCE}"
    fi

    # TODO: rework TZ into fo.ts and remove harmony-temporal
    export TZ="Europe/Brussels"
    node --import tsx/esm --harmony-temporal node/src/fo.ts "import" --to "${TARGET}" "${SOURCE}"
}

import "Workspaces/Jean/Automatic Upload J/"
import "Workspaces/Marie-Line/Automatic Upload/"

ok "Done"
