#!/usr/bin/env bash

set -o errexit

# shellcheck source-path=SCRIPTDIR/../../../packages/jehon/usr/bin/
. jh-lib

PCLOUD="${HOME}/pCloudDrive"
TARGET="${PCLOUD}/Workspaces/Famille/A ranger/"

jh_value "PCLOUD" "${PCLOUD}"
jh_value "TARGET" "${TARGET}"

if [ ! -d "${TARGET}" ]; then
    jh_fatal "Could not access target ${TARGET}"
fi

import() {
    NAME="$1"
    SOURCE="${PCLOUD}/$1"
    shift

    jh_info "Importing $NAME"
    if [ ! -d "${SOURCE}" ]; then
        jh_fatal "Could not read source ${SOURCE}"
    fi
    "${JH_PKG_FOLDER}"/bin/fo "import" --to "${TARGET}" "${SOURCE}"
}

import "Workspaces/Jean/Automatic Upload J/"
import "Workspaces/Marie-Line/Automatic Upload/"

ok "Done"
