---

- name: "Ensure jehon-service-headless is present"
  when: jehon_headless
  ansible.builtin.apt:
    pkg:
      - "jehon-service-headless"

- name: Set default tty
  when: >
    not virtual
    and jehon_tty | int > 0
  ansible.builtin.systemd:
    name: jehon-chvt@{{ jehon_tty }}.service
    enabled: true
    state: started
