---
- name: Do reload daemon
  listen: Jh_cloud.systemctl_reload
  when: not virtual
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: false
  notify: Jh_cloud.remount

- name: Do restart cloud mount
  listen: Jh_cloud.remount
  when: not virtual
  with_items: "{{ mount_list }}"
  ansible.builtin.systemd:
    name: jehon-cloud@{{ item }}.service
    state: "{{ 'restarted' if jh_cloud_start else 'stopped' }}"
  changed_when: false
