---
#
# Desktop side
#
- name: Setup WSL env
  when: false
  block:
    - name: Setup google-chrome repository and packages
      when: "'google-chrome-stable' not in ansible_facts.packages"
      ansible.builtin.command:
        cmd: "/usr/sbin/jh-install-google-chrome"
      changed_when: true
