concurrent = 2
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "vps"
  url = "https://gitlab.com"
  id = XXXXXXXXXx
  token = "XXXXXXXXXX"
  token_obtained_at = XXXXXXXXXX
  token_expires_at = XXXXXXXXXX
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 0
    network_mtu = 0
#########################################3
    image = "docker:latest"
    privileged = true
    volumes = ["/cache", "/certs"]
#########################################3
