---
- name: Copy script files for synology
  block:
    # script_folder: /volume1/scripts/scripts
    # https://docs.ansible.com/ansible/latest/collections/community/general/filetree_lookup.html
    - name: Create directories in {{ script_folder }}
      loop: >-
        {{
          lookup('community.general.filetree', 'templates/scripts/')
            | selectattr('state', 'equalto', 'directory')
            | map(attribute='path')
        }}
      ansible.builtin.file:
        path: "{{ script_folder }}/{{ item }}"
        state: directory
        mode: "0777"

    - name: Copy files and templates for synology to {{ script_folder }}
      # Thanks to https://stackoverflow.com/a/41668011/1954789
      loop: >-
        {{
          lookup('community.general.filetree', 'templates/scripts/')
            | selectattr('state', 'equalto', 'file')
            | map(attribute='path')
        }}
      ansible.builtin.template:
        src: "{{ role_path }}/templates/scripts/{{ item }}"
        dest: "{{ script_folder }}/{{ item }}"
        mode: "0755"

    - name: Remove extraneous files for synology
      # https://stackoverflow.com/a/18016700/1954789
      block:
        - name: List files at destination
          # Will be expanded through shell
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              find "{{ script_folder }}" -type f -printf '%P\n' | grep "\S"
          register: host_synology_sync_files_remote
          changed_when: false

        - name: List local files for synology
          ansible.builtin.set_fact:
            host_synology_sync_files_local: >-
              {{
                lookup('community.general.filetree', 'templates/scripts/')
                  | selectattr('state', 'equalto', 'file')
                  | map(attribute='path')
              }}

        - name: Remove files for synology
          with_items: "{{ host_synology_sync_files_remote.stdout_lines }}"
          when: item not in host_synology_sync_files_local
          ansible.builtin.file:
            path: "{{ script_folder }}/{{ item }}"
            state: absent
