on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # At 01:15
    - cron: "15 1 * * *"

env:
  TZ: Europe/Brussels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v4
        with:
          node-version: current
          check-latest: true
          cache: npm

      - run: ./setup.sh
      - run: make dump
      - run: make build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: tmp

  ga-test:
    runs-on: ubuntu-latest
    needs:
      - build
    timeout-minutes: 30
    strategy:
      # Do not stop the rest of the matrix in case of failure
      fail-fast: false
      matrix:
        target:
          - lint
          - python-test
          - scripts-test
          - packages-test
          - infrastructure-test
          - node-test

    steps:
      - uses: actions/checkout@main

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: tmp

      - uses: actions/setup-node@v4
        with:
          node-version: current
          check-latest: true
          cache: npm

      - run: ./setup.sh
      - run: bin/rehydrate.sh

      - run: make --debug=basic "${{ matrix.target }}"

  valid:
    # placeholder for validation of PR
    needs:
      - ga-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"

  build-pages:
    runs-on: ubuntu-latest
    needs:
      - valid
    timeout-minutes: 120
    if: ${{ github.ref_name == 'main' && github.ref_type == 'branch' }}

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v4
        with:
          node-version: current
          check-latest: true
          cache: npm

      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: tmp

      - run: |
          chmod -v +x tmp/python/*/bin/*

      - run: ./setup.sh
      - run: make --debug=basic release

      - name: Upload Pages artifact
        # https://github.com/actions/upload-pages-artifact?tab=readme-ov-file
        uses: actions/upload-pages-artifact@v3
        with:
          path: tmp/publish

  deploy:
    needs: build-pages
    concurrency:
      group: release-${{ github.ref_name }}
      # cancel-in-progress: true
      # https://github.com/actions/deploy-pages
    if: ${{ github.ref_name == 'main' && github.ref_type == 'branch' }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
