
on:
  push:
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: packages-updated

concurrency:
  group: release-${{ github.ref_name }}
  # cancel-in-progress: true

jobs:
  ga-test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        target:
          - build
          - lint
          - python-test
          - scripts-test
          - packages-test
          - infrastructure-test

    steps:
    - uses: actions/checkout@main

    # TODO: should be used only on publish
    - uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - run: ./setup.sh
    - run: make "${{ matrix.target }}"

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.ref_name == 'main' && github.ref_type == 'branch' }}

    steps:
      - uses: actions/checkout@main

      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - run: ./setup.sh
      - run: make dump
      - run: make release
